### ISSUE TITLE
Week 3 .html is too large, so github isn't allowing upload

### ISSUE THREAD

**Issue by maczokni** [maczokni/crimemapping_textbook_bookdown#1]
I tried the python script from this answer: https://stackoverflow.com/questions/38815784/knitr-html-output-too-large but it didn't work for me. Need to think about what is being stored there (possibly some data/shapefiles) and how we can not store it in there

**Comment by jjmedinaariza** [comment]
I modified the rmarkdown file for this week. I think the problem was that you were using too many interactive maps. The original session didn't. So, somehow, you must have set tmap_mode("View") at an earlier point and left it like that. I now set up tmap_mode("plot") at the outset of week 3 and that sorts the problem. At first I wasn't sure what was the problem so I also deleted the gif at the end. It probably wasnt necessary, so maybe you want to restore it?

**Comment by jjmedinaariza** [comment]
You still need to rebuild the book and then push it up. I did not use travis for my own repo, so I won't try this in case I mess something up. I have been doing this from my British desktop and still getting into trouble with utf8. I don't know whats going on. The rendered html file for week 3 has all the apostrophes looking weird.

**Comment by maczokni** [comment]
It works woop woop!
